package com.mycompany.myapp.domain;

import java.util.Random;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicLong;

public class CadastroAlunoTestSamples {

    private static final Random random = new Random();
    private static final AtomicLong longCount = new AtomicLong(random.nextInt() + (2 * Integer.MAX_VALUE));
    private static final AtomicInteger intCount = new AtomicInteger(random.nextInt() + (2 * Short.MAX_VALUE));

    public static CadastroAluno getCadastroAlunoSample1() {
        return new CadastroAluno()
            .id(1L)
            .matricula("matricula1")
            .grupo("grupo1")
            .nome("nome1")
            .cep("cep1")
            .endereco("endereco1")
            .qd("qd1")
            .lote("lote1")
            .endnumero("endnumero1")
            .bairro("bairro1")
            .municipio("municipio1")
            .uf("uf1")
            .fone("fone1")
            .certidao("certidao1")
            .termo("termo1")
            .cartorio("cartorio1")
            .naturalidade("naturalidade1")
            .rg("rg1")
            .cpf("cpf1")
            .nis("nis1")
            .cras("cras1")
            .filiacaoPai("filiacaoPai1")
            .paiTelefone("paiTelefone1")
            .paiNaturalidade("paiNaturalidade1")
            .paiUf("paiUf1")
            .paiRg("paiRg1")
            .paiCpf("paiCpf1")
            .paiNis("paiNis1")
            .paiTituloEleitor("paiTituloEleitor1")
            .paiZona("paiZona1")
            .paiSecao("paiSecao1")
            .paiMunicipio("paiMunicipio1")
            .filiacaoMae("filiacaoMae1")
            .maeTelefone("maeTelefone1")
            .maeNaturalidade("maeNaturalidade1")
            .maeUf("maeUf1")
            .maeRg("maeRg1")
            .maeCpf("maeCpf1")
            .maeNis("maeNis1")
            .maeTituloEleitor("maeTituloEleitor1")
            .maeZona("maeZona1")
            .maeSecao("maeSecao1")
            .maeMunicipio("maeMunicipio1")
            .nomeEscola("nomeEscola1")
            .anoCursando("anoCursando1")
            .obs("obs1")
            .medicacaoDesc("medicacaoDesc1")
            .alergiaDesc("alergiaDesc1")
            .historicoMedico("historicoMedico1")
            .rendaFamiliar("rendaFamiliar1")
            .pessoasTrabalham(1)
            .numPessoasLar(1)
            .beneficios("beneficios1")
            .tipoResidenciaDesc("tipoResidenciaDesc1")
            .situacaoResidenciaDesc("situacaoResidenciaDesc1")
            .contatoEmergencia("contatoEmergencia1")
            .foneEmergencia("foneEmergencia1")
            .relacaoEmergencia("relacaoEmergencia1")
            .fotoAluno("fotoAluno1")
            .fotoMae("fotoMae1");
    }

    public static CadastroAluno getCadastroAlunoSample2() {
        return new CadastroAluno()
            .id(2L)
            .matricula("matricula2")
            .grupo("grupo2")
            .nome("nome2")
            .cep("cep2")
            .endereco("endereco2")
            .qd("qd2")
            .lote("lote2")
            .endnumero("endnumero2")
            .bairro("bairro2")
            .municipio("municipio2")
            .uf("uf2")
            .fone("fone2")
            .certidao("certidao2")
            .termo("termo2")
            .cartorio("cartorio2")
            .naturalidade("naturalidade2")
            .rg("rg2")
            .cpf("cpf2")
            .nis("nis2")
            .cras("cras2")
            .filiacaoPai("filiacaoPai2")
            .paiTelefone("paiTelefone2")
            .paiNaturalidade("paiNaturalidade2")
            .paiUf("paiUf2")
            .paiRg("paiRg2")
            .paiCpf("paiCpf2")
            .paiNis("paiNis2")
            .paiTituloEleitor("paiTituloEleitor2")
            .paiZona("paiZona2")
            .paiSecao("paiSecao2")
            .paiMunicipio("paiMunicipio2")
            .filiacaoMae("filiacaoMae2")
            .maeTelefone("maeTelefone2")
            .maeNaturalidade("maeNaturalidade2")
            .maeUf("maeUf2")
            .maeRg("maeRg2")
            .maeCpf("maeCpf2")
            .maeNis("maeNis2")
            .maeTituloEleitor("maeTituloEleitor2")
            .maeZona("maeZona2")
            .maeSecao("maeSecao2")
            .maeMunicipio("maeMunicipio2")
            .nomeEscola("nomeEscola2")
            .anoCursando("anoCursando2")
            .obs("obs2")
            .medicacaoDesc("medicacaoDesc2")
            .alergiaDesc("alergiaDesc2")
            .historicoMedico("historicoMedico2")
            .rendaFamiliar("rendaFamiliar2")
            .pessoasTrabalham(2)
            .numPessoasLar(2)
            .beneficios("beneficios2")
            .tipoResidenciaDesc("tipoResidenciaDesc2")
            .situacaoResidenciaDesc("situacaoResidenciaDesc2")
            .contatoEmergencia("contatoEmergencia2")
            .foneEmergencia("foneEmergencia2")
            .relacaoEmergencia("relacaoEmergencia2")
            .fotoAluno("fotoAluno2")
            .fotoMae("fotoMae2");
    }

    public static CadastroAluno getCadastroAlunoRandomSampleGenerator() {
        return new CadastroAluno()
            .id(longCount.incrementAndGet())
            .matricula(UUID.randomUUID().toString())
            .grupo(UUID.randomUUID().toString())
            .nome(UUID.randomUUID().toString())
            .cep(UUID.randomUUID().toString())
            .endereco(UUID.randomUUID().toString())
            .qd(UUID.randomUUID().toString())
            .lote(UUID.randomUUID().toString())
            .endnumero(UUID.randomUUID().toString())
            .bairro(UUID.randomUUID().toString())
            .municipio(UUID.randomUUID().toString())
            .uf(UUID.randomUUID().toString())
            .fone(UUID.randomUUID().toString())
            .certidao(UUID.randomUUID().toString())
            .termo(UUID.randomUUID().toString())
            .cartorio(UUID.randomUUID().toString())
            .naturalidade(UUID.randomUUID().toString())
            .rg(UUID.randomUUID().toString())
            .cpf(UUID.randomUUID().toString())
            .nis(UUID.randomUUID().toString())
            .cras(UUID.randomUUID().toString())
            .filiacaoPai(UUID.randomUUID().toString())
            .paiTelefone(UUID.randomUUID().toString())
            .paiNaturalidade(UUID.randomUUID().toString())
            .paiUf(UUID.randomUUID().toString())
            .paiRg(UUID.randomUUID().toString())
            .paiCpf(UUID.randomUUID().toString())
            .paiNis(UUID.randomUUID().toString())
            .paiTituloEleitor(UUID.randomUUID().toString())
            .paiZona(UUID.randomUUID().toString())
            .paiSecao(UUID.randomUUID().toString())
            .paiMunicipio(UUID.randomUUID().toString())
            .filiacaoMae(UUID.randomUUID().toString())
            .maeTelefone(UUID.randomUUID().toString())
            .maeNaturalidade(UUID.randomUUID().toString())
            .maeUf(UUID.randomUUID().toString())
            .maeRg(UUID.randomUUID().toString())
            .maeCpf(UUID.randomUUID().toString())
            .maeNis(UUID.randomUUID().toString())
            .maeTituloEleitor(UUID.randomUUID().toString())
            .maeZona(UUID.randomUUID().toString())
            .maeSecao(UUID.randomUUID().toString())
            .maeMunicipio(UUID.randomUUID().toString())
            .nomeEscola(UUID.randomUUID().toString())
            .anoCursando(UUID.randomUUID().toString())
            .obs(UUID.randomUUID().toString())
            .medicacaoDesc(UUID.randomUUID().toString())
            .alergiaDesc(UUID.randomUUID().toString())
            .historicoMedico(UUID.randomUUID().toString())
            .rendaFamiliar(UUID.randomUUID().toString())
            .pessoasTrabalham(intCount.incrementAndGet())
            .numPessoasLar(intCount.incrementAndGet())
            .beneficios(UUID.randomUUID().toString())
            .tipoResidenciaDesc(UUID.randomUUID().toString())
            .situacaoResidenciaDesc(UUID.randomUUID().toString())
            .contatoEmergencia(UUID.randomUUID().toString())
            .foneEmergencia(UUID.randomUUID().toString())
            .relacaoEmergencia(UUID.randomUUID().toString())
            .fotoAluno(UUID.randomUUID().toString())
            .fotoMae(UUID.randomUUID().toString());
    }
}
