package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CadastroAlunoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCadastroAlunoAllPropertiesEquals(CadastroAluno expected, CadastroAluno actual) {
        assertCadastroAlunoAutoGeneratedPropertiesEquals(expected, actual);
        assertCadastroAlunoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCadastroAlunoAllUpdatablePropertiesEquals(CadastroAluno expected, CadastroAluno actual) {
        assertCadastroAlunoUpdatableFieldsEquals(expected, actual);
        assertCadastroAlunoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCadastroAlunoAutoGeneratedPropertiesEquals(CadastroAluno expected, CadastroAluno actual) {
        assertThat(expected)
            .as("Verify CadastroAluno auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCadastroAlunoUpdatableFieldsEquals(CadastroAluno expected, CadastroAluno actual) {
        assertThat(expected)
            .as("Verify CadastroAluno relevant properties")
            .satisfies(e -> assertThat(e.getDataCadastro()).as("check dataCadastro").isEqualTo(actual.getDataCadastro()))
            .satisfies(e -> assertThat(e.getMatricula()).as("check matricula").isEqualTo(actual.getMatricula()))
            .satisfies(e -> assertThat(e.getGrupo()).as("check grupo").isEqualTo(actual.getGrupo()))
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getDn()).as("check dn").isEqualTo(actual.getDn()))
            .satisfies(e -> assertThat(e.getCep()).as("check cep").isEqualTo(actual.getCep()))
            .satisfies(e -> assertThat(e.getEndereco()).as("check endereco").isEqualTo(actual.getEndereco()))
            .satisfies(e -> assertThat(e.getQd()).as("check qd").isEqualTo(actual.getQd()))
            .satisfies(e -> assertThat(e.getLote()).as("check lote").isEqualTo(actual.getLote()))
            .satisfies(e -> assertThat(e.getEndnumero()).as("check endnumero").isEqualTo(actual.getEndnumero()))
            .satisfies(e -> assertThat(e.getBairro()).as("check bairro").isEqualTo(actual.getBairro()))
            .satisfies(e -> assertThat(e.getMunicipio()).as("check municipio").isEqualTo(actual.getMunicipio()))
            .satisfies(e -> assertThat(e.getUf()).as("check uf").isEqualTo(actual.getUf()))
            .satisfies(e -> assertThat(e.getFone()).as("check fone").isEqualTo(actual.getFone()))
            .satisfies(e -> assertThat(e.getCertidao()).as("check certidao").isEqualTo(actual.getCertidao()))
            .satisfies(e -> assertThat(e.getTermo()).as("check termo").isEqualTo(actual.getTermo()))
            .satisfies(e -> assertThat(e.getCartorio()).as("check cartorio").isEqualTo(actual.getCartorio()))
            .satisfies(e -> assertThat(e.getNaturalidade()).as("check naturalidade").isEqualTo(actual.getNaturalidade()))
            .satisfies(e -> assertThat(e.getRg()).as("check rg").isEqualTo(actual.getRg()))
            .satisfies(e -> assertThat(e.getCpf()).as("check cpf").isEqualTo(actual.getCpf()))
            .satisfies(e -> assertThat(e.getNis()).as("check nis").isEqualTo(actual.getNis()))
            .satisfies(e -> assertThat(e.getCras()).as("check cras").isEqualTo(actual.getCras()))
            .satisfies(e -> assertThat(e.getFiliacaoPai()).as("check filiacaoPai").isEqualTo(actual.getFiliacaoPai()))
            .satisfies(e -> assertThat(e.getPaiTelefone()).as("check paiTelefone").isEqualTo(actual.getPaiTelefone()))
            .satisfies(e -> assertThat(e.getPaiNaturalidade()).as("check paiNaturalidade").isEqualTo(actual.getPaiNaturalidade()))
            .satisfies(e -> assertThat(e.getPaiUf()).as("check paiUf").isEqualTo(actual.getPaiUf()))
            .satisfies(e -> assertThat(e.getPaiRg()).as("check paiRg").isEqualTo(actual.getPaiRg()))
            .satisfies(e -> assertThat(e.getPaiDataNascimento()).as("check paiDataNascimento").isEqualTo(actual.getPaiDataNascimento()))
            .satisfies(e -> assertThat(e.getPaiCpf()).as("check paiCpf").isEqualTo(actual.getPaiCpf()))
            .satisfies(e -> assertThat(e.getPaiNis()).as("check paiNis").isEqualTo(actual.getPaiNis()))
            .satisfies(e -> assertThat(e.getPaiTituloEleitor()).as("check paiTituloEleitor").isEqualTo(actual.getPaiTituloEleitor()))
            .satisfies(e -> assertThat(e.getPaiZona()).as("check paiZona").isEqualTo(actual.getPaiZona()))
            .satisfies(e -> assertThat(e.getPaiSecao()).as("check paiSecao").isEqualTo(actual.getPaiSecao()))
            .satisfies(e -> assertThat(e.getPaiMunicipio()).as("check paiMunicipio").isEqualTo(actual.getPaiMunicipio()))
            .satisfies(e -> assertThat(e.getFiliacaoMae()).as("check filiacaoMae").isEqualTo(actual.getFiliacaoMae()))
            .satisfies(e -> assertThat(e.getMaeTelefone()).as("check maeTelefone").isEqualTo(actual.getMaeTelefone()))
            .satisfies(e -> assertThat(e.getMaeNaturalidade()).as("check maeNaturalidade").isEqualTo(actual.getMaeNaturalidade()))
            .satisfies(e -> assertThat(e.getMaeUf()).as("check maeUf").isEqualTo(actual.getMaeUf()))
            .satisfies(e -> assertThat(e.getMaeRg()).as("check maeRg").isEqualTo(actual.getMaeRg()))
            .satisfies(e -> assertThat(e.getMaeDataNascimento()).as("check maeDataNascimento").isEqualTo(actual.getMaeDataNascimento()))
            .satisfies(e -> assertThat(e.getMaeCpf()).as("check maeCpf").isEqualTo(actual.getMaeCpf()))
            .satisfies(e -> assertThat(e.getMaeNis()).as("check maeNis").isEqualTo(actual.getMaeNis()))
            .satisfies(e -> assertThat(e.getMaeTituloEleitor()).as("check maeTituloEleitor").isEqualTo(actual.getMaeTituloEleitor()))
            .satisfies(e -> assertThat(e.getMaeZona()).as("check maeZona").isEqualTo(actual.getMaeZona()))
            .satisfies(e -> assertThat(e.getMaeSecao()).as("check maeSecao").isEqualTo(actual.getMaeSecao()))
            .satisfies(e -> assertThat(e.getMaeMunicipio()).as("check maeMunicipio").isEqualTo(actual.getMaeMunicipio()))
            .satisfies(e -> assertThat(e.getNomeEscola()).as("check nomeEscola").isEqualTo(actual.getNomeEscola()))
            .satisfies(e -> assertThat(e.getAnoCursando()).as("check anoCursando").isEqualTo(actual.getAnoCursando()))
            .satisfies(e -> assertThat(e.getTurno()).as("check turno").isEqualTo(actual.getTurno()))
            .satisfies(e -> assertThat(e.getMediaEscolar()).as("check mediaEscolar").isEqualTo(actual.getMediaEscolar()))
            .satisfies(e -> assertThat(e.getPrioritario()).as("check prioritario").isEqualTo(actual.getPrioritario()))
            .satisfies(e -> assertThat(e.getObs()).as("check obs").isEqualTo(actual.getObs()))
            .satisfies(e -> assertThat(e.getComportamentoCasa()).as("check comportamentoCasa").isEqualTo(actual.getComportamentoCasa()))
            .satisfies(e ->
                assertThat(e.getComportamentoEscola()).as("check comportamentoEscola").isEqualTo(actual.getComportamentoEscola())
            )
            .satisfies(e -> assertThat(e.getDeficiencia()).as("check deficiencia").isEqualTo(actual.getDeficiencia()))
            .satisfies(e -> assertThat(e.getAdaptacoes()).as("check adaptacoes").isEqualTo(actual.getAdaptacoes()))
            .satisfies(e -> assertThat(e.getMedicacao()).as("check medicacao").isEqualTo(actual.getMedicacao()))
            .satisfies(e -> assertThat(e.getMedicacaoDesc()).as("check medicacaoDesc").isEqualTo(actual.getMedicacaoDesc()))
            .satisfies(e -> assertThat(e.getAlergia()).as("check alergia").isEqualTo(actual.getAlergia()))
            .satisfies(e -> assertThat(e.getAlergiaDesc()).as("check alergiaDesc").isEqualTo(actual.getAlergiaDesc()))
            .satisfies(e -> assertThat(e.getHistoricoMedico()).as("check historicoMedico").isEqualTo(actual.getHistoricoMedico()))
            .satisfies(e -> assertThat(e.getRendaFamiliar()).as("check rendaFamiliar").isEqualTo(actual.getRendaFamiliar()))
            .satisfies(e -> assertThat(e.getPessoasTrabalham()).as("check pessoasTrabalham").isEqualTo(actual.getPessoasTrabalham()))
            .satisfies(e -> assertThat(e.getNumPessoasLar()).as("check numPessoasLar").isEqualTo(actual.getNumPessoasLar()))
            .satisfies(e -> assertThat(e.getBeneficioSocial()).as("check beneficioSocial").isEqualTo(actual.getBeneficioSocial()))
            .satisfies(e -> assertThat(e.getBeneficios()).as("check beneficios").isEqualTo(actual.getBeneficios()))
            .satisfies(e -> assertThat(e.getTipoResidencia()).as("check tipoResidencia").isEqualTo(actual.getTipoResidencia()))
            .satisfies(e -> assertThat(e.getTipoResidenciaDesc()).as("check tipoResidenciaDesc").isEqualTo(actual.getTipoResidenciaDesc()))
            .satisfies(e -> assertThat(e.getSituacaoResidencia()).as("check situacaoResidencia").isEqualTo(actual.getSituacaoResidencia()))
            .satisfies(e ->
                assertThat(e.getSituacaoResidenciaDesc()).as("check situacaoResidenciaDesc").isEqualTo(actual.getSituacaoResidenciaDesc())
            )
            .satisfies(e -> assertThat(e.getContatoEmergencia()).as("check contatoEmergencia").isEqualTo(actual.getContatoEmergencia()))
            .satisfies(e -> assertThat(e.getFoneEmergencia()).as("check foneEmergencia").isEqualTo(actual.getFoneEmergencia()))
            .satisfies(e -> assertThat(e.getRelacaoEmergencia()).as("check relacaoEmergencia").isEqualTo(actual.getRelacaoEmergencia()))
            .satisfies(e -> assertThat(e.getAutorizacao()).as("check autorizacao").isEqualTo(actual.getAutorizacao()))
            .satisfies(e -> assertThat(e.getFotoAluno()).as("check fotoAluno").isEqualTo(actual.getFotoAluno()))
            .satisfies(e -> assertThat(e.getFotoMae()).as("check fotoMae").isEqualTo(actual.getFotoMae()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCadastroAlunoUpdatableRelationshipsEquals(CadastroAluno expected, CadastroAluno actual) {
        // empty method
    }
}
